services:
    ds_topic.topic.filter:
        parent: api_platform.doctrine.orm.search_filter
        arguments:
            - { uuid: exact }
        tags:
            - { name: api_platform.filter, id: ds_topic.topic.filter }
